# Generated by Django 4.2.1 on 2024-01-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
