# Generated by Django 4.2.1 on 2024-02-06 11:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_customuser_alter_user_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
