# Generated by Django 4.2.1 on 2024-01-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_app', '0003_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
